version: 2
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
      languages:
        python:
          python_version: 3
  pep8:
    enabled: true

  sonar-python:
    enabled: true
    config:
      test_patterns:
        - tests/**