engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3

plugins:
  pylint:
    enabled: true
    checks:
      import-error:
        enabled: false
