plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
      languages:
        python:
          python_version: 3

  pylint:
    enabled: true
    checks:
      import-error:
        enabled: false
