KEDRO_AZURE_BLOB_TEMP_DIR_NAME = "kedro-azureml-temp"
KEDRO_AZURE_RUNNER_CONFIG = "KEDRO_AZURE_RUNNER_CONFIG"
AZURE_SUBSCRIPTION_ID = "AZURE_SUBSCRIPTION_ID"
FILL_IN_DOCKER_IMAGE = "<fill in docker image>"
