name: Update Check Run
description: Updates a check run for a specific job in a pull request
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  pull_request_number:
    description: 'Pull Request number'
    required: true
  github_job:
    description: 'GitHub job'
    required: true
  conclusion:
    description: 'Job Conclusion'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      id: update-check-run
      if: ${{ always() }}
      env:
        number: ${{ inputs.pull_request_number }}
        job: ${{ inputs.job }}
        # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
        conclusion: ${{ inputs.conclusion }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { data: pull } = await github.rest.pulls.get({
            ...context.repo,
            pull_number: process.env.number
          });
          const ref = pull.head.sha;

          const { data: checks } = await github.rest.checks.listForRef({
            ...context.repo,
            ref
          });

          const check = checks.check_runs.filter(c => c.name === process.env.job);

          const { data: result } = await github.rest.checks.update({
            ...context.repo,
            check_run_id: check[0].id,
            status: 'completed',
            conclusion: process.env.conclusion
          });

          return result;
